# Generated by Django 4.0.1 on 2022-02-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subode', models.CharField(max_length=10)),
                ('regulation', models.CharField(max_length=5)),
                ('dept', models.CharField(max_length=45)),
                ('subject_name', models.CharField(max_length=80)),
                ('credits', models.CharField(max_length=2)),
                ('sem', models.CharField(max_length=1)),
            ],
        ),
    ]
