# Generated by Django 4.0.1 on 2022-02-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='subode',
            new_name='subcode',
        ),
    ]
